name: coffee_repository
description: A repository for managing coffee data and business logic.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  http: ^1.2.2
  image: ^4.2.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  meta: ^1.15.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
