name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Run tests with coverage
      run: flutter test --coverage --test-randomize-ordering-seed random
      
    - name: Install lcov
      run: sudo apt-get update && sudo apt-get install -y lcov
      
    - name: Filter coverage (exclude files from analysis_options.yaml)
      run: |
        lcov --remove coverage/lcov.info "**/l10n/generated/**" --ignore-errors unused --output-file coverage/lcov.filtered
        mv coverage/lcov.filtered coverage/lcov.info
        
    - name: Check coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2
      with:
        path: 'coverage/lcov.info'
        min_coverage: 85
        exclude: '**/l10n/generated/**'
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: 'coverage/lcov.info'
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
