name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Install lcov
      run: sudo apt-get update && sudo apt-get install -y lcov
      
    - name: Run main app tests with coverage
      run: flutter test --coverage --test-randomize-ordering-seed random
      
    - name: Run package tests with coverage
      run: |
        cd packages/coffee_repository
        flutter test --coverage
        cd ../..
        
    - name: Merge coverage reports
      run: |
        # Adjust package paths to be relative to project root
        sed 's|SF:lib/|SF:packages/coffee_repository/lib/|g' packages/coffee_repository/coverage/lcov.info > packages/coffee_repository/coverage/lcov_adjusted.info
        
        # Merge coverage files
        lcov --add-tracefile coverage/lcov.info \
             --add-tracefile packages/coffee_repository/coverage/lcov_adjusted.info \
             --output-file coverage/merged.info
        
        # Filter out generated files
        lcov --remove coverage/merged.info "**/l10n/generated/**" --ignore-errors unused --output-file coverage/lcov.info
        
    - name: Check coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2
      with:
        path: 'coverage/lcov.info'
        min_coverage: 90
        exclude: '**/l10n/generated/**'
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: 'coverage/lcov.info'
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
